name: Android CD

on:
  push:
    tags:
    - android-**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Tag name
      id: get_version
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      
    - name: mv app file
      env:
        SOURCE_TAG: ${{ steps.get_version.outputs.SOURCE_TAG }}
      run: 
         echo $SOURCE_TAG
         mv test test/$SOURCE_TAG/test.apk
