name: Android CI

on:
  workflow_dispatch:
    inputs:
      variants:
        type: choice
        description: select variants
        options: 
        - Debug
        - Staging
        
      message:
        description: release notes
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }}"
    
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew assemble${{ github.event.inputs.variants }}
    
    - name: Upload APK
      run: pwd
#      uses: actions/upload-artifact@v3
#      with:
#        name: my-artifact
#        path: path/to/artifact/
      
      
